### ISSUE TITLE
Swagger jsDocs

### ISSUE THREAD

**Issue by ericdowell** [ericdowell/whirlwind-api#41]
## Is your feature request related to a problem? Please describe.
Swagger page is incomplete and does not list all of the endpoints/entities/examples/etc.

## Describe the solution you'd like
- [x] Add common schema for `ErrorBlock` at the top of `errors/index.ts` and update `registerSwagger` in `src/routes.ts` to include the following in the `apis` array:
```ts
resolve(__dirname, 'errors/index.ts'),
resolve(__dirname, 'errors/index.js'),
```
- [x] Add swagger jsDocs to all entities (except Session). 
- [ ] Add swagger jsDocs to all controllers. Double check existing Swagger jsDocs, e.g. `/user/role/assign`
    - [x] For 422 responses include `ErrorBlock` schema ref as an array within a `errors` key: `{ message: string, errors: [{ location: string, msg: string, param: string }] }`. Use ref like User already is within controllers, e.g. `$ref: '#/components/schemas/ErrorBlock'`
    - [x] Based on ACL find all possible places we will throw a 401 for unauthorized users and apply this to responses in swagger. Response should only include `message` since we'll only ever get: `{"message": "This action is unauthorized."}`
     - [x] Include `419` for all non GET/HEAD/OPTION endpoints, response should only include `message` since we'll only ever get: `{"message": "CSRF token mismatch."}`
    - [x] Detail all remaining status codes `410`/`500` and so on with the correct response key/values where they apply in context of controller.
    - [x] ~~Add header `Set-Cookie XSRF-TOKEN` and `Set-Cookie whirlwind.sid` to all responses for all swagger paths.~~

## Additional context
- https://github.com/ericdowell/whirlwind-api/issues/37

**Comment by larzhole** [comment]
@ericdowell 

> Add header Set-Cookie XSRF-TOKEN and Set-Cookie whirlwind.sid to all responses.

What is the purpose of this?
Are you saying you want me to do something like this where we register middleware?
```typescript
  app.use((req: Request, res: Response, next: NextFunction) => {
    res.header('Set-Cookie', 'XSRF-TOKEN')
    res.header('Set-Cookie', 'whirlwind.sid')
    next()
  })
```

**Comment by ericdowell** [comment]
@larzhole 
This issue is for Swagger, this task is listed for applying to all swagger jsdocs.

I'm asking for the following `https://github.com/OAI/OpenAPI-Specification/issues/1237#issuecomment-423955715`

**Comment by ericdowell** [comment]
@larzhole As I think about adding this to every `responses:` subkey for every `path` I start to see it will add a lot of text.

So let's skip adding these two headers to Swagger docs and let it be assumed for now.
